[phases.setup]
nixPkgs = [
  "php",
  "php82Extensions.gd",
  "php82Extensions.mbstring",
  "php82Extensions.zip",
  "php82Extensions.pdo_mysql",
  "php82Extensions.opcache",
  "phpPackages.composer",
  "nodejs_18"
]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install --omit=dev"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"