[phases.setup]
nixPkgs = ["nodejs_18", "php", "composer"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install --omit=dev"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"